title: minigenerator
email: contact@juliendargelos.com
description: The simplest way to generate files on the go.
url: https://juliendargelos.github.io/minigenerator
githubUsername: juliendargelos
twitterUsername: juliendargelos
codepenUsername: juliendargelos
themeColor: blue # green, blue, orange, purple, grey
remote_theme: alexcarpenter/material-jekyll-theme
sass:
  style: compressed
