title: minigenerator
email: contact@juliendargelos.com
description: The simplest way to generate files on the go.
url: https://juliendargelos.github.io/minigenerator
githubUsername: juliendargelos
twitterUsername: juliendargelos
codepenUsername: juliendargelos
remote_theme: juliendargelos/material-jekyll-theme
navigation:
  Overview: /
  Options: /options/
  Rules: /rules/
  Built-In: /built-in/
